apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: commitly
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: harsimrand/commitly-auth-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: REDIS_HOST
              value: auth-redis-cache
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: main-db-secret
                  key: DATABASE_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: GOOGLE_CLIENT_SECRET
