apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-proxy-config
  namespace: commitly
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen 80;
            location /api/v1/auth {
                proxy_pass http://auth-service;
            }
        }
    }
