apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
  namespace: commitly
  labels:
    app: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          image: harsimrand/commitly-next-app:v0
          ports:
            - containerPort: 3000
          env:
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: next-app-secret
                  key: AUTH_URL
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: next-app-secret
                  key: AUTH_SECRET
            - name: AUTH_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: next-app-secret
                  key: AUTH_GOOGLE_CLIENT_ID
            - name: AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: next-app-secret
                  key: AUTH_GOOGLE_CLIENT_SECRET
