apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: commitly
data:
  redis.conf: |
    appendonly yes
    save 60 1
    protected-mode no
    dir /data
    maxmemory 512mb
    maxmemory-policy allkeys-lru
